name = "Defencemancer"
default_targets = ["win32", "win64", "macos", "lovejs"]
build_directory = "../bin"  # Assuming bin is in the root directory

# Explicitly include files in the src directory
love_files = [
    "main.lua",  # main.lua is in the same directory as makelove.toml
    "*",         # Include everything in the src directory
]